name: e2e-test-android

jobs:
    build_android_for_e2e:
        type: build
        params:
            platform: android
            profile: e2e-test

    maestro_test:
        needs: [build_android_for_e2e]
        type: maestro
        params:
            build_id: ${{ needs.build_android_for_e2e.outputs.build_id }}
            flow_path:
                - __tests__/e2e/home.yaml
                - __tests__/e2e/lookup-clean.yaml
                - __tests__/e2e/lookup-incidents.yaml
                - __tests__/e2e/lookup-not-found.yaml
                - __tests__/e2e/history.yaml
                - __tests__/e2e/legal.yaml
                - __tests__/e2e/theme.yaml
