import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safe: { flex: 1 },
  content: {
    width: "100%",
    maxWidth: 600,
    alignSelf: "center",
    paddingBottom: 44,
  },
  hero: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 54,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
  },
  title: {
    fontSize: 37,
    lineHeight: 43,
    fontWeight: "700",
    letterSpacing: -1.5,
    marginTop: 27,
  },
  subtitle: { fontSize: 16, lineHeight: 24, marginTop: 12, maxWidth: 300 },
  main: { paddingHorizontal: 20, marginTop: -26, gap: 30 },
  form: {
    padding: 20,
    borderRadius: 26,
    gap: 17,
    shadowColor: "#592609",
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  formTitle: {
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "600",
    letterSpacing: -0.5,
  },
  error: { fontSize: 14, lineHeight: 20 },
  submit: {
    minHeight: 56,
    borderRadius: 16,
    padding: 14,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  submitText: { fontSize: 17, fontWeight: "600" },
  recent: { gap: 15 },
  recentHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    fontSize: 23,
    lineHeight: 29,
    fontWeight: "600",
    letterSpacing: -0.6,
  },
  historyCount: { fontSize: 14 },
  empty: {
    borderRadius: 22,
    padding: 20,
    gap: 14,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  emptyIcon: {
    width: 45,
    height: 45,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyCopy: { flex: 1, gap: 6 },
  emptyTitle: { fontSize: 16, lineHeight: 22, fontWeight: "500" },
  emptyText: { fontSize: 14, lineHeight: 22 },
  historyList: { borderRadius: 22, overflow: "hidden", paddingHorizontal: 16 },
  historyRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 86,
    gap: 13,
    paddingVertical: 14,
  },
  historyIcon: {
    width: 43,
    height: 43,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  historyCopy: { flex: 1, gap: 5 },
  historyPlate: { fontSize: 20, letterSpacing: 0.8, fontWeight: "600" },
  historyAge: { fontSize: 13, lineHeight: 19 },
  smallText: { fontSize: 14, lineHeight: 21 },
  footer: { alignItems: "center", gap: 6 },
  privacyLink: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  disclaimer: {
    fontSize: 12,
    lineHeight: 19,
    textAlign: "center",
    maxWidth: 290,
  },
});

export default styles;
