import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    safe: { flex: 1 },
    header: {
        paddingHorizontal: 24,
        paddingTop: 12,
        paddingBottom: 16,
        width: '100%',
        maxWidth: 600,
        alignSelf: 'center',
    },
    content: {
        width: '100%',
        maxWidth: 600,
        alignSelf: 'center',
        paddingHorizontal: 24,
        paddingBottom: 28,
        gap: 28,
    },
    intro: { gap: 10, paddingTop: 10 },
    eyebrow: { fontSize: 11, lineHeight: 17, fontWeight: '800', letterSpacing: 1.6 },
    title: { fontSize: 31, lineHeight: 37, fontWeight: '800', letterSpacing: -1.1 },
    subtitle: { fontSize: 16, lineHeight: 24, maxWidth: 320 },
    form: { borderRadius: 24, borderWidth: 1, padding: 20, gap: 18 },
    formTitle: { fontSize: 18, lineHeight: 25, fontWeight: '700' },
    error: { fontSize: 15, lineHeight: 22 },
    sources: {
        borderTopWidth: StyleSheet.hairlineWidth,
        paddingTop: 15,
        flexDirection: 'row',
        gap: 8,
        alignItems: 'center',
    },
    sourceText: { fontSize: 12, lineHeight: 18, flex: 1 },
    recent: { gap: 12 },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
    },
    sectionTitle: {
        fontSize: 20,
        lineHeight: 27,
        fontWeight: '800',
        letterSpacing: -0.4,
        flex: 1,
    },
    clear: { minHeight: 48, minWidth: 48, justifyContent: 'center', alignItems: 'flex-end' },
    action: { fontSize: 14, fontWeight: '600' },
    historyRow: {
        minHeight: 80,
        paddingVertical: 14,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        borderBottomWidth: StyleSheet.hairlineWidth,
    },
    historyIcon: {
        width: 44,
        height: 44,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
    },
    historyCopy: { flex: 1, gap: 3 },
    historyPlate: { fontSize: 18, lineHeight: 25, fontWeight: '700', letterSpacing: 0.8 },
    historyAge: { fontSize: 14, lineHeight: 21 },
    empty: {
        borderWidth: 1,
        borderStyle: 'dashed',
        borderRadius: 18,
        padding: 18,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
    },
    emptyTitle: { fontSize: 16, lineHeight: 23, fontWeight: '600' },
    privacy: {
        borderTopWidth: StyleSheet.hairlineWidth,
        paddingTop: 22,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        minHeight: 72,
    },
    privacyIcon: {
        width: 42,
        height: 42,
        borderRadius: 21,
        alignItems: 'center',
        justifyContent: 'center',
    },
    privacyTitle: { fontSize: 15, lineHeight: 22, fontWeight: '600' },
});

export default styles;
